### ISSUE TITLE
France Medias Monde is having trouble with SDK implementation

### ISSUE THREAD

**Issue by bprobert** [Parsely/parsely-android#10]
Since most of this is a foreign language to me, I'm just going to copy and paste the email and attachments.

I’m reaching out on the behalf of tech team that seems to have trouble implementing your SDK on our Android apps (we didn’t start on iOS yet).
 
Here are the issues noted by the team :
 
“For your information, here the current version of the app available on google play and the version of SDK that have been integrated.
Attached you will find the log for the 2 main crashes for France24 3.X ANDROID but we have the same issues for RFI ANDROID.
 
 
--- the apps
France24 3.X ANDROID
Version Name 3.6.3 Version Code 143307
SDK Parsely : 2.0
 
RFI ANDROID
Version Name 2.1.1.3 Version Code 102113
SDK Parsely : 2.0
 
--- the logs for F24 only
1. Error ParselyTracker.java line 450
com.parsely.parselyandroid.ParselyTracker$FlushQueue.doInBackground
Attached file see
error_1_com.france24.androidapp_issue_702_crash_5A4E19C30143000156E6D0EF69472511_bf84ce4b0ead4b4abace833078222863_0_v1.txt
 
2. Error ParselyTracker.java line 145
com.parsely.parselyandroid.ParselyTracker.sendBatchRequest
Attached file see
error_2_com.france24.androidapp_issue_710_crash_5880F97B02E700015341726C72FE7043_725dff7cfbc4476db59f1325e05a7145_0_v1.txt”
 
Also, they ask if you have a ticketing tool allowing us to send directly to you or anyone in ParseLy their questions and in order to move faster on the integration ?
 
[error_1_com.france24.androidapp_issue_702_crash_5A4E19C30143000156E6D0EF69472511_bf84ce4b0ead4b4abace833078222863_0_v1 (1).txt](https://github.com/Parsely/parsely-android/files/687845/error_1_com.france24.androidapp_issue_702_crash_5A4E19C30143000156E6D0EF69472511_bf84ce4b0ead4b4abace833078222863_0_v1.1.txt)

[error_2_com.france24.androidapp_issue_710_crash_5880F97B02E700015341726C72FE7043_725dff7cfbc4476db59f1325e05a7145_0_v1 (1).txt](https://github.com/Parsely/parsely-android/files/687846/error_2_com.france24.androidapp_issue_710_crash_5880F97B02E700015341726C72FE7043_725dff7cfbc4476db59f1325e05a7145_0_v1.1.txt)

**Comment by bprobert** [comment]
Hey Emmett, any update on this?

**Comment by emmett9001** [comment]
Sorry to let this one sit around so long. Do we know if these crashes are happening regularly, or under some particular set of conditions? Also, they can file issues directly on this issue tracker in the future.

**Comment by emmett9001** [comment]
I've added some error checking to the functions that were crashing for them. They can try running their tests again with current master.
