### ISSUE TITLE
trackURL on Samsung Galaxy S6 recorded as tablet

### ISSUE THREAD

**Issue by wdbetts** [Parsely/parsely-android#11]
Similar to [this issue on parsely-ios](https://github.com/Parsely/parsely-ios/issues/10), tracks sent by parsely-android `trackURL` are getting recorded as a tablet instead of mobile when sent from a Samsung Galaxy S6. 

Here is what gets logged
`
01-08 20:20:04.311: I/System.out(29760): [Parsely] {ts=1.483932004318E9, data={idsite=****.com, os_version=23, manufacturer=samsung, appname=Krazy Coupon Lady, urlref=parsely_mobile_sdk, parsely_site_uuid=XXXX, os=android}, url=http://thekrazycouponlady.com/2016/12/06/moneymaker-12-count-sharpie-markers-at-staples21501/}
01-08 20:20:04.321: I/System.out(29760): [Parsely] Data {"events":[{"ts":"1483931965.910000","url":"http://thekrazycouponlady.com/2017/01/08/spectrum-cooking-spray-0-14-at-target-today-only/"},{"ts":"1483931944.164000","url":"http://thekrazycouponlady.com/2017/01/08/5-hottest-deals-on-kcl-moneymakers-0-99-huggies-more/"},{"ts":"1483931950.913000","url":"http://thekrazycouponlady.com/2017/01/08/nature-made-vitamins-as-low-as-2-75-at-target/"},{"ts":"1483931969.256000","url":"http://thekrazycouponlady.com/2017/01/08/toy-clearance-at-walmart-disney-princess-castles-as-low-as-25-00/"},{"ts":"1483931989.964000","url":"http://thekrazycouponlady.com/2016/12/06/moneymaker-12-count-sharpie-markers-at-staples21501/"}],"data":{"idsite":"****.com","os_version":"23","manufacturer":"samsung","appname":"Krazy Coupon Lady","urlref":"parsely_mobile_sdk","parsely_site_uuid":"XXXX","os":"android"}}
`

The Parse.ly dashboard then reports this:
![screen shot 2017-01-08 at 8 32 41 pm](https://cloud.githubusercontent.com/assets/719249/21756690/b310165e-d5e1-11e6-982e-5b2f490b2a46.png)

**Comment by emmett9001** [comment]
@wdbetts Looks like this is again caused by an issue with the python user_agents module. I've opened an [issue](https://github.com/selwin/python-user-agents/issues/73) on that repo and added a patch to Parse.ly's backend system, which should be deployed in the next week or two.
