### ISSUE TITLE
Docs reference a 3 month window that started in February

### ISSUE THREAD

**Issue by ezramechaber** [Parsely/parsely-android#117]
Hi, I'm a customer from Bloomberg. The mobile app docs on parsely's website reference a 3 month window in a beta:

>Breaking changes coming soon
>On February 5, 2024 we released a beta version of a new major release of the Parse.ly Android SDK, version 4.0.0. We intend to run this beta for 3 months and solicit your feedback prior to the production release. If you migrate from 3.x to 4.x SDK, then see our [migration guide](https://github.com/Parsely/parsely-android/blob/main/MIGRATION.md).

Seems like the docs could use an update to clarify if Parsely is in 4.0.0 or still in beta.

**Comment by wzieba** [comment]
Hi, thank you for the report! I can confirm that Parsely Android SDK is stable in [`4.1.0`](https://github.com/Parsely/parsely-android/releases/tag/4.1.0). We'll update the documentation soon.

**Comment by wzieba** [comment]
The documentation is now updated, thank you again for the report!
