### ISSUE TITLE
Removed Permission

### ISSUE THREAD

**Issue by mypplication** [Parsely/parsely-android#12]
Documentation is not up to date
here
https://www.parse.ly/sdk/android/
and here:
https://github.com/Parsely/parsely-android

` <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
is not needed

**Comment by emmett9001** [comment]
@mypplication Thanks! How do you know this permission is no longer needed? Please feel free to open a pull request that makes this change.

**Comment by mypplication** [comment]
I've just read the code. :)
context.openFileInput and context.openFileOutput do not require any permission
