### ISSUE TITLE
Context memory leak

### ISSUE THREAD

**Issue by mypplication** [Parsely/parsely-android#13]
https://github.com/Parsely/parsely-android/blob/71d6f1ecb22416ee39b6b65322d9dc8a6262fd47/parsely/parselyandroid/ParselyTracker.java#L329

You must get the application context and not just the context (which can be an activity)

`this.context = c.getApplicationContex()`

**Comment by emmett9001** [comment]
@mypplication Thanks for finding this. Please feel free to open a pull request that makes and tests this change.
