### ISSUE TITLE
get app name

### ISSUE THREAD

**Issue by mypplication** [Parsely/parsely-android#14]
https://github.com/Parsely/parsely-android/blob/71d6f1ecb22416ee39b6b65322d9dc8a6262fd47/parsely/parselyandroid/ParselyTracker.java#L320

Why do not use `context.getPackageManager().getApplicationLabel(context.getApplicationInfo())`

In an application resource name "app_name" is not mandatory

**Comment by emmett9001** [comment]
@mypplication This was probably an oversight when the SDK was first written - thanks for the information. Please feel free to open a pull request that makes this change.
