### ISSUE TITLE
Refactor - replace AsyncTask to new approaches - Android 11

### ISSUE THREAD

**Issue by MBratkowski** [Parsely/parsely-android#23]
Hello,

Do you have plans to replace deprecated AsyncTask classes with some new approaches?
We use a Parsley SDK in our project. Currently, we are planning the migration of our application to Android 11, but in the new version of Android, AsyncTask class is deprecated. We adjusted our codebase to new approaches, but still, we have a Parsely SDK which is using internal AsyncTasks.

https://developer.android.com/reference/android/os/AsyncTask

Best regards,
Mateusz

**Comment by emmett9001** [comment]
@MBratkowski Thanks for bringing this to our attention. Our engineers will take a look at the deprecation details and prioritize the update appropriately.

**Comment by wzieba** [comment]
hi @MBratkowski, thank you for the report. As the Parsely Android SDK is now offered via MavenCentral, the usage of AsyncTasks in SDK shouldn't be a blocker for migration of your app. 

I'll close this issue, but please feel free to re-open in any case. Thanks!
