### ISSUE TITLE
Remove Write External Storage permission 

### ISSUE THREAD

**Issue by kpuneet** [Parsely/parsely-android#3]
Why we need to "Write External Storage" permission , when we can store the data on internal Storage , it  adds for more permission to be given to the Apps which is not writing anything on external storage.

**Comment by emmett9001** [comment]
HI @kpuneet, thanks for pointing this out. I've opened pull request #4 that removes the external storage permission. The example app still seems to function properly on my simulator with the permission removed. If you'd like, please give the branch a try in your own app's context and let me know here how it works. If everything looks alright, we can merge.

**Comment by emmett9001** [comment]
Duplicated by #6
