### ISSUE TITLE
Remove AdMob dependency

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/parsely-android#32]
We only use it to generate a unique ID, but there's no strong requirement for it to be tied to the advertising ID. Generating a UUID and persisting it ought to be just as good.

**Comment by wzieba** [comment]
The AdMob dependency was removed in the past.

Currently, we use `play-services-ads-identifier` to generate the identifier or we fall back to locally-generated UUID if the device doesn't have Google Play Services.

With the latter approach, there's an issue described in #59.

I'll close this issue as part of the repository maintenance, as it's now obsolete. Please feel free to re-open if I missed something!
