### ISSUE TITLE
Use of UUID instead of Advertising ID

### ISSUE THREAD

**Issue by nseidm1** [Parsely/parsely-android#5]
generateSiteUuid() retrieves the device UUID which changes upon factory reset, and is different for each user of the device. The Advertising ID is the standard and expected way to identify a particular user.

http://developer.android.com/google/play-services/id.html

**Comment by emmett9001** [comment]
Thanks @nseidm1. I'll prioritize this issue for the next few weeks.

**Comment by mypplication** [comment]
So? When can you update your SDK with another solution ?
Thx

**Comment by cwisecarver** [comment]
Fixed by #15. Will be included in the next release.
